class Setting < Struct.new(:api_key, :api_secret, :token_key, :token_secret)
	VERSION = 1.2
	OLD_KEYS = %W(APIKEY APISECRET TOKENKEY TOKENSECRET)
	attr_reader :filename

	def initialize(autoload = true)
		@filename = ENV["SETTING_FILE"] || "setting.db"
		return unless autoload
		wizard unless File.exists? @filename
		self.read
		wizard unless self.check?
	end

	# Modify setting in an intaractive way.
	def wizard
		puts "Please entry below informations,"
		print "API key [#{self.api_key}]: "
		value = gets.chomp
		self.api_key = value unless value.empty?

		print "API sercet key [#{self.api_secret}]: "
		value = gets.chomp
		self.api_secret = value unless value.empty?

		print "Token key [#{self.token_key}]: "
		value = gets.chomp
		self.token_key = value unless value.empty?

		print "Token secret key [#{self.token_secret}]: "
		value = gets.chomp
		self.token_secret = value unless value.empty?

		self.write!
		puts self.to_s
	end

	REGEXP_SETTING_PAIR = /^(?<key>\w+)\s*=\s*(?<bracket>'|")(?<value>[[:word:]]*)\k<bracket>$/
	def read
		puts "Read setting..."
		IO.readlines(@filename).each do |line|
			REGEXP_SETTING_PAIR.match line.chomp do |md|
				key = md[:key].to_sym
				value = md[:value]
				self[key] = value if self.members.include? key
				puts "WARNING! Found old option: #{md[:key]}. You may run setting_upgrade.rb before starting ke__ri robot." if OLD_KEYS.include? md[:key]
			end																																																																
		end
	end

	def write!
		File.open @filename, "w" do |io|
			io.puts %(# Notice! Do NOT add option which is not effective. They will be cleared with next wizard.)
			io.puts %(# Generated by v#{VERSION}.)
			self.members.each do |key|
				io.puts %(#{key} = "#{self[key]}")
			end
		end
	end

	def check?
		self.members.each do |key|
			next unless self[key].nil? or self[key].empty?
			puts %(Missing necessary key: #{key})
			return false
		end
		true
	end

	def to_s
		result = "{\n"
		self.members.each do |key|
			result << %(\t#{key} => #{self[key]}\n)
		end
		result << "}"
	end
end
